name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v12.10.0
      uses: actions/setup-node@v1
      with:
        node-version: v12.10.0
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm test
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
    - uses: chrislennon/action-aws-cli@v1.1
    - name: Deploy to DigitalOcean Spaces
      run: aws configure set default.s3.signature_version s3v2 && aws s3 sync ./dist s3://${{ secrets.SPACES_BUCKET }}/${{ github.sha }} --endpoint=https://${{ secrets.SPACES_REGION }}.digitaloceanspaces.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.SPACES_REGION }}
